export const signUpClick = () => ({type: 'signUpClick'})
export const signInClick = () => ({type: 'signInClick'})
export const authChanged = (payload) => ({type: 'authChanged', payload})
export const authPassed = (payload) => ({type: 'authPassed', payload})
export const logOut = () => ({type: 'logOut'})
export const copyFromStorage = (payload) => ({type: 'copyFromStorage', payload})
export const setUsers = (payload) => ({type: 'setUsers', payload})
export const selectUser = (payload) => ({type: 'selectUser', payload})
export const selectAll = () => ({type: 'selectAll'})